version: '3.7'
services:
  # some-app:
  #   build: ../
  #   image: cypress/someAppImageName
  #   ports:
  #     - "3000:3000"

  electron-desktop-tests:
    image: "cypress/included:6.3.0"
    environment:
      - CYPRESS_baseUrl=https://www.discoverireland.ie
    working_dir: /cypress-setup
    command: "--headless --spec cypress/integration/desktop/*.js"
    volumes:
      - ./:/cypress-setup
      - /dev/shm:/dev/shm

  electron-mobile-tests:
    image: "cypress/included:6.3.0"
    environment:
      - CYPRESS_baseUrl=https://www.discoverireland.ie
    working_dir: /cypress-setup
    command: "--config viewportWidth=375,viewportHeight=667,userAgent=iPhone --headless --spec cypress/integration/mobile/*.js"
    volumes:
      - ./:/cypress-setup
      - /dev/shm:/dev/shm